
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "gps-uex"
    token:
      secure: "99e6e32e93adbd7041192838595bffc55f79ad59"
jdk:
  - oraclejdk8
script:
  - mvn clean -Dmaven.test.skip=true org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
